FROM python:3.6
RUN pip install --upgrade pip

ENV INSTALL_DIR /home/web-scrapper-microservice
RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

USER nobody

ENTRYPOINT ["celery"]
CMD ["worker", "-A", "tasks", "--loglevel=info"]